name: tf-hrrrenv
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python==3.12.2
  - tensorflow
  - conda-forge::herbie-data
  - conda-forge::wgrib2
  - conda-forge::opencv
  - conda-forge::notebook
  - conda-forge::sqlite[version='>=3.45']
  - matplotlib==3.10.0
  - conda-forge::scikit-image
  - conda-forge::gdal
  - conda-forge::python-dotenv
  - conda-forge::seaborn
  - conda-forge::pyhdf
  - conda-forge::netcdf4
  - earthaccess
  - conda-forge::dask
  - goes2go
  - conda-forge::pydot
  - conda-forge::rioxarray
  - conda-forge::adjusttext
  - scikit-gstat
prefix: /home/mgraca/miniconda3/envs/tf-hrrrenv
