name: hrrrenv
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python==3.12.2
  - conda-forge::herbie-data
  - conda-forge::wgrib2
  - conda-forge::opencv
  - conda-forge::notebook
  - sqlite[version='>=3.49']
  - libsqlite
  - conda-forge::scikit-image
  - conda-forge::gdal
  - conda-forge::python-dotenv
  - conda-forge::seaborn
  - conda-forge::pyhdf
  - conda-forge::netcdf4
  - conda-forge::earthaccess
  - conda-forge::dask
  - conda-forge::goes2go
  - conda-forge::pydot
  - conda-forge::rioxarray
  - conda-forge::tensorflow-gpu
  - conda-forge::adjusttext
  - conda-forge::scikit-gstat
prefix: /home/mgraca/miniconda3/envs/hrrrenv
